apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finops-notebooks.fullname" . }}-cleanup
  labels:
  {{- include "finops-notebooks.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "finops-notebooks.fullname" . }}-cleanup
  labels:
  {{- include "finops-notebooks.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch", "list", "watch"]
  - apiGroups: ["finops.krateo.io"]
    resources: ["notebooks"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "finops-notebooks.fullname" . }}-cleanup
  labels:
  {{- include "finops-notebooks.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ include "finops-notebooks.fullname" . }}-cleanup
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "finops-notebooks.fullname" . }}-cleanup
  apiGroup: rbac.authorization.k8s.io